kind: pipeline
name: default

clone:
  depth: 5

steps:
  - name: build go
    image: golang:1.12
    commands:
      - go build
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -a -tags netgo -o release/linux/amd64/drone-git-notify-log
