---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  depth: 5

steps:
- name: build go
  image: golang:1.12
  commands:
  - go build
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -a -tags netgo -o release/linux/amd64/drone-slack-notify-log

- name: blackbox test
  image: golang:1.15
  commands:
  - ./drone-slack-notify-log
  environment:
    DRONE_HOST: https://cloud.drone.io
    DRONE_TOKEN:
      from_secret: drone_token
    PLUGIN_CHANNEL: C013L74BY4E
    PLUGIN_STEP_NUMBER: 2
    SLACK_TOKEN:
      from_secret: slack_token
  when:
    event:
      exclude:
      - pull_request

- name: build docker image (dry_run)
  image: plugins/docker
  settings:
    dry-run: true
    password:
      from_secret: docker_hub_password
    repo: matsubara0507/slack-notify-log
    username: matsubara0507
  when:
    event:
      exclude:
      - pull_request

- name: push docker image
  image: plugins/docker
  settings:
    password:
      from_secret: docker_hub_password
    repo: matsubara0507/slack-notify-log
    username: matsubara0507
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

...
